import React, { useState } from "react";
import {
  voiceEngines,
  languageNames,
  toneOptions,
} from "../Data/newAchorData";
import InputField from "../Components/Resusable/InputField";
import Button from "../Components/Resusable/Button";
import VideoPlayer from "../Components/Resusable/VideoPlayer";
import TestVideo from "../../assets/video1.mp4";
import TestAudio from "../../assets/audio.mp3";

const AINewsAnchor = ({ onChange = () => {} }) => {
  const [selectedEngine, setSelectedEngine] = useState("");
  const [selectedTone, setSelectedTone] = useState("");
  const [selectedLanguage, setSelectedLanguage] = useState("");
  const [topic, setTopic] = useState("");
  const [outputType, setOutputType] = useState("");

  const currentEngine = voiceEngines.find((ve) => ve.value === selectedEngine);
  const toneList = currentEngine ? currentEngine.supportedTones : [];
  const languageList = currentEngine ? currentEngine.supportedLanguages : [];

  const handleEngineChange = (e) => {
    const engine = e.target.value;
    setSelectedEngine(engine);
    setSelectedTone("");
    setSelectedLanguage("");
    onChange({ engine, tone: "", language: "" });
  };

  const handleToneChange = (e) => {
    const tone = e.target.value;
    setSelectedTone(tone);
    onChange({ engine: selectedEngine, tone, language: selectedLanguage });
  };

  const handleLanguageChange = (e) => {
    const lang = e.target.value;
    setSelectedLanguage(lang);
    onChange({ engine: selectedEngine, tone: selectedTone, language: lang });
  };

  const handleGenerate = (type) => {
    if (!topic || !selectedEngine || !selectedTone || !selectedLanguage) {
      alert("⚠️ Please complete all selections and enter a topic.");
      return;
    }
    setOutputType(type);
  };

  const outputComponents = {
    script: (
      <p className="text-base text-gray-700 leading-relaxed">
        📰 <strong>[Sample Script]</strong> Breaking news on <strong>{topic}</strong>. This is a demonstration script generated by the AI Anchor.
      </p>
    ),
    audio: (
      <audio controls className="w-full mt-2">
        <source src={TestAudio} type="audio/mp3" />
        Your browser does not support the audio element.
      </audio>
    ),
    video: (
      <div className="space-y-2 w-full">
        <p className="text-lg font-semibold text-gray-800">🎥 Video Preview</p>
        <VideoPlayer video={TestVideo} />
      </div>
    ),
  };

  return (
    <div className="w-full max-w-7xl mx-auto bg-white shadow-xl rounded-3xl p-8 md:p-5 transition-all duration-300">
      {/* Header */}
      <div className="mb-10 border-b border-gray-300 pb-4 text-center">
        <h1 className="text-2xl font-extrabold text-gray-800">AI News Anchor</h1>
        <p className="text-sm md:text-lg text-blue-600 mt-2">
          Generate voice, script, and video summaries for breaking news topics.
        </p>
      </div>

      {/* Main Grid */}
      <div className="grid lg:grid-cols-2 gap-10">
        {/* Left: Form */}
        <div className="space-y-6 bg-gray-50 p-6 rounded-2xl border border-gray-200 shadow-sm">
          <InputField
            label="News Topic"
            placeholder="e.g., AI Election Report, Global Warming"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
          />

          {/* Voice Engine */}
          <div className="space-y-1">
            <label className="text-sm font-semibold text-gray-700">
              Select Voice Engine
            </label>
            <select
              className="w-full border border-gray-300 rounded-xl px-4 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none text-sm"
              value={selectedEngine}
              onChange={handleEngineChange}
            >
              <option value="">Choose a voice style</option>
              {voiceEngines.map((engine) => (
                <option key={engine.value} value={engine.value}>
                  {engine.label}
                </option>
              ))}
            </select>
          </div>

          {/* Tone */}
          <div className="space-y-1">
            <label className="text-sm font-semibold text-gray-700">
              News Tone
            </label>
            <select
              className="w-full border border-gray-300 rounded-xl px-4 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none text-sm"
              value={selectedTone}
              onChange={handleToneChange}
              disabled={!selectedEngine}
            >
              <option value="">Choose tone</option>
              {toneList.map((tone) => (
                <option key={tone} value={tone}>
                  {toneOptions[tone]}
                </option>
              ))}
            </select>
          </div>

          {/* Language */}
          <div className="space-y-1">
            <label className="text-sm font-semibold text-gray-700">
              News Language
            </label>
            <select
              className="w-full border border-gray-300 rounded-xl px-4 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none text-sm"
              value={selectedLanguage}
              onChange={handleLanguageChange}
              disabled={!selectedEngine}
            >
              <option value="">Choose language</option>
              {languageList.map((lang) => (
                <option key={lang} value={lang}>
                  {languageNames[lang] || lang}
                </option>
              ))}
            </select>
          </div>

          {/* Generate Buttons */}
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 pt-4">
            {[
              { label: "Generate Script", type: "script" },
              { label: "Generate Audio", type: "audio" },
              { label: "Generate Video", type: "video" },
            ].map((btn) => (
              <Button
                key={btn.type}
                content={btn.label}
                click={() => handleGenerate(btn.type)}
                condition={true}
                data={true}
                color={true}
                style="max-w-[150px] hover:scale-105 transition"
              />
            ))}
          </div>
        </div>

        {/* Right: Output */}
        <div className="space-y-3">
          <h2 className="text-lg font-semibold text-gray-800">Generated Output</h2>
          <div className="w-full border border-gray-300 rounded-xl p-4 bg-gray-50 shadow-inner min-h-[420px] flex items-center justify-center ">
            {outputType ? (
              outputComponents[outputType]
            ) : (
              <p className="text-gray-400 italic text-sm text-center">
                Choose an output type above to generate content.
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default AINewsAnchor;
